### 00. PyTorch Fundamentals

Timestamp: 1:14:00 - https://youtu.be/Z_ikDlimN6A?t=4440&si=0MbmtYJsTSlTceYB

In [1]:
!nvidia-smi

Mon Jun  2 12:09:43 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.02                 Driver Version: 576.02         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   59C    P8              6W /   50W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.0+cu126


## Introduction to Tensors

### Creating tensors

PyTorch tensors are creating using torch.tensor()



In [3]:
# scalar
s = torch.tensor(7)
s

tensor(7)

In [4]:
s.ndim # Number of dimensions (scalar has zero)

0

In [5]:
# Get value back as python int type
s.item()

7

In [6]:
# vector
v = torch.tensor([7,7])
v

tensor([7, 7])

In [7]:
v.ndim # Vector has one dimension

1

In [8]:
v.shape

torch.Size([2])

In [9]:
# matrix
X = torch.tensor([
    [5, 6],
    [7, 8]
])

In [10]:
X.ndim # Matrices have two dimensions

2

In [11]:
X.shape # return the size of each dimension of the tensor

torch.Size([2, 2])

In [12]:
X.size() # alias for .shape

torch.Size([2, 2])

In [13]:
# Tensor
T = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])

In [14]:
T.ndim # Three dimensions (same as number of opening square brackets '[' )

3

In [15]:
T.size()

torch.Size([1, 3, 3])

In [16]:
# indexing & slicing tensors
T[0] # show's first dimension of tensor T

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
# to get at the 2nd dimension-
T[0][0]

tensor([1, 2, 3])

In [18]:
# or
T[0][1]

tensor([4, 5, 6])